# Generated by Django 5.1.1 on 2025-01-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_subject_data_blooms_level_subject_data_bl1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject_data",
            name="bl11",
            field=models.CharField(default="I-scheme", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject_data",
            name="bl12",
            field=models.CharField(default="Remember", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject_data",
            name="m11",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject_data",
            name="m12",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject_data",
            name="q11",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject_data",
            name="q12",
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject_data",
            name="scheme",
            field=models.CharField(
                choices=[("I-scheme", "I-scheme"), ("K-scheme", "K-scheme")],
                default="I-scheme",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="subject_data",
            name="qb",
            field=models.FileField(upload_to="question_banks/"),
        ),
    ]
