# Generated by Django 5.1.1 on 2025-01-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_subject_data_bl11_subject_data_bl12_subject_data_m11_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject_data",
            name="bl13",
            field=models.CharField(default="Remember", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject_data",
            name="bl14",
            field=models.CharField(default="Remember", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject_data",
            name="m13",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject_data",
            name="m14",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject_data",
            name="q13",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject_data",
            name="q14",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
    ]
