# Generated by Django 5.1.1 on 2025-01-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_subject_data_m13"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject_data",
            name="m14",
            field=models.IntegerField(default=0),
        ),
    ]
