# Generated by Django 5.1.1 on 2025-01-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_subject_data_m14"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject_data",
            name="bl13",
            field=models.CharField(default="Remember", max_length=50),
        ),
        migrations.AlterField(
            model_name="subject_data",
            name="bl14",
            field=models.CharField(default="Remember", max_length=50),
        ),
        migrations.AlterField(
            model_name="subject_data",
            name="q13",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="subject_data",
            name="q14",
            field=models.CharField(default="", max_length=500),
        ),
    ]
