# Generated by Django 5.1.1 on 2025-01-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_subject_data_bl13_alter_subject_data_bl14_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject_data",
            name="bl15",
            field=models.CharField(default="Remember", max_length=50),
        ),
        migrations.AddField(
            model_name="subject_data",
            name="bl16",
            field=models.CharField(default="Remember", max_length=50),
        ),
        migrations.AddField(
            model_name="subject_data",
            name="m15",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subject_data",
            name="m16",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subject_data",
            name="q15",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="subject_data",
            name="q16",
            field=models.CharField(default="", max_length=500),
        ),
    ]
