# Generated by Django 5.1.1 on 2025-02-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_subject_data_bl15_subject_data_bl16_subject_data_m15_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject_data",
            name="test",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
